### ISSUE TITLE
Update readme with info on diff to official remotes integration

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-remotes-HASS#15]
The official remotes integration by @azogue is under active development, but it would be useful to clarify the functionality of this CC vs the official

**Comment by azogue** [comment]
I'll try to make a PR on the README asap :)

**Comment by steveelsbury** [comment]
If the documentation being added could include a quick example of how to migrate from the CC to the official version that would be great, especially as the readme.md for this CC now states that we should be switching to use the official component.

**Comment by steveelsbury** [comment]
I just realised that the wiki I quoted was on the sensors component, not the remotes component. I was not aware these had been split. What prompted me to post originally is that since the HA 107 upgrade I am seeing this in the log: 

Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:269
Integration: Hass.io (documentation, issues)
First occurred: April 18, 2020, 2:29:15 PM (2 occurrences)
Last logged: April 18, 2020, 2:37:48 PM

Platform error device_tracker.huesensor - cannot import name 'ENTITY_ID_FORMAT' from 'homeassistant.components.device_tracker.const' (/usr/src/homeassistant/homeassistant/components/device_tracker/const.py)
Component error: hacs - Integration 'hacs' not found. Platform error device_tracker.huesensor - cannot import name 'ENTITY_ID_FORMAT' from 'homeassistant.components.device_tracker.const' (/usr/src/homeassistant/homeassistant/components/device_tracker/const.py)

**Comment by azogue** [comment]
> I just realised that the wiki I quoted was on the sensors component, not the remotes component. I was not aware these had been split. What prompted me to post originally is that since the HA 107 upgrade I am seeing this in the log:
> Platform error device_tracker.huesensor - cannot import name 'ENTITY_ID_FORMAT' from 'homeassistant.components.device_tracker.const' 

Hi @steveelsbury ,

It seems like the `huesensor` CC breaks with HA 107 because some import from HA has been moved or removed. Only suggestion to quick fix that is to remove the `device_tracker.py` from the CC (in case you're not using it).

BTW, Is there any reason for you to use that CC now that sensors are in the main hue and remotes are removed from there? Are you using any of the FoH sensors that are only recognized in that CC?

**Comment by steveelsbury** [comment]
My use-case for this CC was to write automations that respond to Hue Switch button presses. I do not know if that requires the tracker or not - I just followed the original instructions when I first installed the CC.  If this is now catered for in HA then I can switch back to that no worries. I did look at the wiki for the built-in functionality and could not see any equivalent functionality.

**Comment by grantclem** [comment]
Bit confused with the remotes - all I see in the Hue integration are battery % sensors.... is there something that I am missing? What events are fired with the remotes? Can't find any documentation anywhere.

**Comment by azogue** [comment]
> Bit confused with the remotes - all I see in the Hue integration are battery % sensors.... is there something that I am missing? What events are fired with the remotes? Can't find any documentation anywhere.

Hi @grantclem 

It is very briefly commented on the Hue docs. The main idea is that you can **create automations  using remote presses as 'device triggers'**, from the device details of any remote (which should be listed in the devices list).

**Comment by azogue** [comment]
> My use-case for this CC was to write automations that respond to Hue Switch button presses. I do not know if that requires the tracker or not - I just followed the original instructions when I first installed the CC. If this is now catered for in HA then I can switch back to that no worries. I did look at the wiki for the built-in functionality and could not see any equivalent functionality.

Hi @steveelsbury 

Old Hass-sensors CC is deprecated with modern HA, and even Hass-remotes CC is now unneeded.

We'll try to explain how to make a quick migration, but in the meanwhile, you can check my comments (like this one: https://github.com/robmarkcole/Hue-remotes-HASS/issues/14#issuecomment-616092774) on how to migrate. There is equivalent functionality right now, by using 2 new CC's instead of this one.

**Comment by steveelsbury** [comment]
OK, I commented out the assignment of the device tracker to the hue sensors and the error went away and everything still seems to work, so thanks for that.

Given what a great platform HA is and what great work all contributors do, it is such a shame that the documentation is so woefully inadequate - while this remains true, HA will remain of interest to techies only. Thanks very much indeed for that comment link and it looks like I should be able to work from it to try an unlink myself from the CC. I can't help feeling that good, informative articles such as that one should have a place somewhere on the main HA wiki and not just be buried somewhere is a forum thread! No wait.... you already said you were going to do a migration doc! :-)

Anyway, thanks again.

**Comment by grantclem** [comment]
> > Bit confused with the remotes - all I see in the Hue integration are battery % sensors.... is there something that I am missing? What events are fired with the remotes? Can't find any documentation anywhere.
> 
> Hi @grantclem
> 
> It is very briefly commented on the Hue docs. The main idea is that you can **create automations using remote presses as 'device triggers'**, from the device details of any remote (which should be listed in the devices list).

Thanks, finally figured it out using Appdaemon. The only thing I can find are battery sensors for each remote and nothing else
